var paths = [['Materials/odd_audio_video/sin-23/sin-23.mp4', "No way!"],
    ['Materials/odd_audio_video/sin-01/sin-01.mp4', "Great!"],
    ['Materials/odd_audio_video/sin-35/sin-35.mp4', "Good job!"],
    ['Materials/odd_audio_video/sar-44/sar-44.mp4', "Who cares?"],
    ['Materials/odd_audio_video/sar-10/sar-10.mp4', "Sign me up!"],
    ['Materials/odd_audio_video/sar-28/sar-28.mp4', "Definitely."],
    ['Materials/odd_audio_video/sar-04/sar-04.mp4', "Yeah, right."],
    ['Materials/odd_audio_video/sin-19/sin-19.mp4', "Please, go on..."],
    ['Materials/odd_audio_video/sin-27/sin-27.mp4', "Totally!"],
    ['Materials/odd_audio_video/sar-18/sar-18.mp4', "My week just keeps getting better!"],
    ['Materials/odd_audio_video/sar-30/sar-30.mp4', "No, he wouldn't!"],
    ['Materials/odd_audio_video/sin-05/sin-05.mp4', "That's interesting."],
    ['Materials/odd_audio_video/sin-33/sin-33.mp4', "Looking good."],
    ['Materials/odd_audio_video/sar-06/sar-06.mp4', "That's just what I needed."],
    ['Materials/odd_audio_video/sin-11/sin-11.mp4', "How awful!"],
    ['Materials/odd_audio_video/sin-39/sin-39.mp4', "Good as new!"],
    ['Materials/odd_audio_video/sin-37/sin-37.mp4', "Well isn't that nice?"],
    ['Materials/odd_audio_video/sar-20/sar-20.mp4', "It's totally safe!"],
    ['Materials/odd_audio_video/sin-15/sin-15.mp4', "Oh yeah, good one!"],
    ['Materials/odd_audio_video/sar-34/sar-34.mp4', "Tell me about it..."],
    ['Materials/odd_audio_video/sin-17/sin-17.mp4', "It's really great to be here!"],
    ['Materials/odd_audio_video/sin-07/sin-07.mp4', "Stop it!"],
    ['Materials/odd_audio_video/sin-25/sin-25.mp4', "Abortions for everybody!"],
    ['Materials/odd_audio_video/sin-45/sin-45.mp4', "Gosh!"],
    ['Materials/odd_audio_video/sin-03/sin-03.mp4', "Good for you!"],
    ['Materials/odd_audio_video/sar-40/sar-40.mp4', "That will be real hard!"],
    ['Materials/odd_audio_video/sin-29/sin-29.mp4', "Right."],
    ['Materials/odd_audio_video/sin-21/sin-21.mp4', "You're a genius."],
    ['Materials/odd_audio_video/sar-08/sar-08.mp4', "Really?"],
    ['Materials/odd_audio_video/sin-09/sin-09.mp4', "I'm so happy for you!"],
    ['Materials/odd_audio_video/sin-13/sin-13.mp4', "This game is great!"],
    ['Materials/odd_audio_video/sar-32/sar-32.mp4', "I would never do that!"],
    ['Materials/odd_audio_video/sin-31/sin-31.mp4', "Wonderful!"],
    ['Materials/odd_audio_video/sar-16/sar-16.mp4', "Way to go!"],
    ['Materials/odd_audio_video/sar-38/sar-38.mp4', "That'll be totally easy!"],
    ['Materials/odd_audio_video/sar-12/sar-12.mp4', "I'd love to see that!"],
    ['Materials/odd_audio_video/sin-43/sin-43.mp4', "I never expected that!"],
    ['Materials/odd_audio_video/sar-42/sar-42.mp4', "You scared the hell out of me!"],
    ['Materials/odd_audio_video/sin-41/sin-41.mp4', "I'd trust him"],
    ['Materials/odd_audio_video/sar-26/sar-26.mp4', "You know, you really need a razor scooter."],
    ['Materials/odd_audio_video/sar-36/sar-36.mp4', "You're too kind!"],
    ['Materials/odd_audio_video/sar-22/sar-22.mp4', "Bummer!"],
    ['Materials/odd_audio_video/sar-14/sar-14.mp4', "Happy? I'm thrilled!"],
    ['Materials/odd_audio_video/sar-24/sar-24.mp4', "Who doesn't?"],
    ['Materials/odd_audio_video/sar-02/sar-02.mp4', "Oh wow!"]];
